---
title: "Homework1"
author: "Ditian Li"
date: "2018/9/20"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

#Problem 1
## Create a data frame
```{r #Problem 1-1}
set.seed(666)
p1_df = tibble(
  z = runif(10, min = 0, max = 5),
  vec_logical = z > 2,
  vec_char = c("a", "b", "c", "d","e","f","g","h","i","j"),
  vec_factor = factor(c("male", "male", "female", "female","male", "male", "female", "female", "female", "female"))
)

```

## Mean
```{r #Problem 1-2}

mean(p1_df$z)
mean(p1_df$vec_logical)
mean(p1_df$vec_char)
mean(p1_df$vec_factor)
```
Mean of the random sample of size 10 from uniform distribution and vec_logical worked, others didn't work, because they are not numeric or logical variable.

##Convert
```{r #Problem 1-3-1, result = "hide"}
as.numeric(p1_df$vec_logical)
as.numeric(p1_df$vec_char )
as.numeric(p1_df$vec_factor)
```
Character vector can't convert in to numeric vector, others could work.

```{r #Problem 1-3-2}
as.numeric(as.factor(p1_df$vec_char))
as.numeric(as.character(p1_df$vec_factor))
```

